rewrote fancy echo messages

diff --git a/functions/check b/functions/check
--- a/functions/check
+++ b/functions/check
@@ -3,7 +3,7 @@
 # Check if command failed, if true abort
 function check_fail {
 	if [[ $EXITSTATUS != 0 ]]; then
-		display_error "Last command returned an error; something may have went wrong. Aborting..." && sleep 2 && exit 99
+		echo_message error "Last command returned an error; something may have went wrong. Aborting..." && sleep 2 && exit 99
 	fi
 }
 
@@ -21,32 +21,32 @@ function check_dependencies {
 	check_packages $PACKAGE
 	EXITSTATUS=$?
 	if [ $EXITSTATUS = 1 ]; then
-		display_warning "Dependency '$PACKAGE' is not present on your system and is required to continue."
-		display_question 'Would you like to install it now? (Y)es, (N)o :' && read REPLY
+		echo_message warning "Dependency '$PACKAGE' is not present on your system and is required to continue."
+		echo_message question 'Would you like to install it now? (Y)es, (N)o :' && read REPLY
 		case $REPLY in
 		# Positive action
 		[Yy]* ) 
-			display_info "Installing '$PACKAGE' installed. Proceeding."
+			echo_message info "Installing '$PACKAGE' installed. Proceeding."
 			# Admin privileges
 			sudo apt install -y $PACKAGE
-			display_success "Package '$PACKAGE' installed. Proceeding."
+			echo_message success "Package '$PACKAGE' installed. Proceeding."
 			;;
 		# Negative action
 		[Nn]* )
-			display_warning "Required dependencies are not present. :/"
+			echo_message warning "Required dependencies are not present. :/"
 			echo "Exiting..."
 			exit 99
 			;;
 		# Error
 		* )
-			display_error '\aInvalid response, please try again.' && check_dependencies
+			echo_message error '\aInvalid response, please try again.' && check_dependencies
 			;;
 		esac
 	else
 		echo "Dependency '$PACKAGE' is installed."
 	fi
 	done
-	display_success "Dependencies are installed. :)"
+	echo_message success "Dependencies are installed. :)"
 	echo "Proceeding."
 }
 
@@ -54,20 +54,20 @@ function check_dependencies {
 function check_distribution {
 	EXITSTATUS=$(which lsb_release &>/dev/null; echo $?)
 	if [[ $EXITSTATUS != 0 ]]; then
-		display_error "\aCan't check which distribution you are using! Aborting."
-		display_error " Aborting..." && sleep 3 && exit 99
+		echo_message error "\aCan't check which distribution you are using! Aborting."
+		echo_message error " Aborting..." && sleep 3 && exit 99
 	else
 		if lsb_release -ds | grep -qE '(Ubuntu|Mint|elementary)'; then
 			echo 'Current distribution is: '$(lsb_release -ds)
-			display_success "Using Ubuntu or an Ubuntu-based distribution. :)"
+			echo_message success "Using Ubuntu or an Ubuntu-based distribution. :)"
 			echo "Proceeding."
 		elif lsb_release -ds | grep -q 'Debian'; then
 			echo 'Current distribution is: '$(lsb_release -ds)
-			display_warning "Using Debian; some functions may require tweaking. :/"
+			echo_message warning "Using Debian; some functions may require tweaking. :/"
 			echo "Proceeding nonetheless."
 		else
-			display_error "\aYou appear to be using a distribution which is not compatible with this script! :("
-			display_error "Proceeding might break the system. Aborting..." && sleep 3 && exit 99
+			echo_message error "\aYou appear to be using a distribution which is not compatible with this script! :("
+			echo_message error "Proceeding might break the system. Aborting..." && sleep 3 && exit 99
 		fi
 	fi
 }
@@ -78,17 +78,17 @@ function check_privileges {
 	if [[ $EUID != 0 ]]; then
 		EXITSTATUS=$(groups $USER | grep -q 'sudo'; echo $?)
 		if [[ $EXITSTATUS != 0 ]]; then
-			display_error "Your user account doesn't have authorization to use these scripts with this computer. Log in as root or as a user with admin privileges."
-			display_info "Exiting..."
+			echo_message error "Your user account doesn't have authorization to use these scripts with this computer. Log in as root or as a user with admin privileges."
+			echo_message info "Exiting..."
 			sleep 5 && exit 99
 		fi
 		# Current user can use 'sudo'
-		display_success "Current user has sudo privileges. :)"
+		echo_message success "Current user has sudo privileges. :)"
 		echo "Proceeding."
 		SUDOCMD="sudo"
 	else
 		# Display warning about being root user
-		display_warning "You are logged in as the root user. This is not recommended. :/"
+		echo_message warning "You are logged in as the root user. This is not recommended. :/"
 		if (whiptail --title "Root User" --yesno "You are logged in as the root user. This is mostly fine, but not recommended.\n\nAre you sure you want to proceed?" 8 64) then
 			echo "Proceeding."
 			SUDOCMD=
@@ -101,14 +101,14 @@ function check_privileges {
 
 function check {
 	# Check sudo
-	display_info "Checking administrative privileges of current user..."
+	echo_message info "Checking administrative privileges of current user..."
 	check_privileges
 	# Check distro
-	display_info "Checking distribution information..."
+	echo_message info "Checking distribution information..."
 	check_distribution
 	# Check dependencies
-	display_info "Checking if dependencies are installed..."
+	echo_message info "Checking if dependencies are installed..."
 	check_dependencies
 	# Done
-	display_success "Check complete."
+	echo_message success "Check complete."
 }
