added password prompt

diff --git a/functions/configure b/functions/configure
--- a/functions/configure
+++ b/functions/configure
@@ -13,50 +13,49 @@ function set_preferences {
 	done < "$GSETTINGS"
 	# Done
 	display_success 'Settings changed successfully.'
-	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 64
 	configure
 }
 
 # Show start-up all start-up applications by modifying the 'NoDisplay' line of their .desktop files
 function display_startup_apps {
 	display_info 'Changing display of startup applications...'
-	display_warning 'Requires admin privileges'
-	$SUDOCMD sed -i "s/NoDisplay=true/NoDisplay=false/g" /etc/xdg/autostart/*.desktop
+	# Admin privileges
+	elevate_privilege "sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop"
 	# Done
 	display_success 'Settings changed successfully.'
-	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 64
 	configure
 }
 
 # Disable Apport
 function disable_apport {
 	display_info 'Disabling apport crash dialogs...'
-	display_warning 'Requires admin privileges'
-	$SUDOCMD sed -i "s/enabled=1/enabled=0/g" /etc/default/apport
+	# Admin privileges
+	elevate_privilege "sed -i 's/enabled=1/enabled=0/g' /etc/default/apport"
 	# Done
 	display_success 'Settings changed successfully.'
-	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
+	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 64
 	configure
 }
 
 # Configure System
 function configure {
 	display_title "Starting 'configure' function..."
-	# Draw window
-	CONF=$(eval `resize` && whiptail \
+	# check exit status
+	exitstatus=$?
+	if [ $exitstatus = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
 		--notags \
 		--title "Configure System" \
 		--menu "\nWhat would you like to do?" \
 		--cancel-button "Go Back" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		32 96 16 \
 		set_preferences		'Set preferred application-specific & desktop settings' \
 		display_startup_apps	'Show all startup applications' \
 		disable_apport		'Disable system crash dialogs' \
 		3>&1 1>&2 2>&3)
-
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		$CONF
 	else
 		main
 	fi
diff --git a/functions/fonts b/functions/fonts
--- a/functions/fonts
+++ b/functions/fonts
@@ -10,8 +10,8 @@ function install_fonts {
 	# Draw window
 	if (eval `resize` && whiptail \
 		--title "Preferred Fonts" \
-		--yesno "Current list of preferred fonts to install: \n\n$(cat $FONTLIST) \n\nProceed with installation?" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		--yesno "Current list of preferred fonts to install: \n\n$(for LINE in $(cat $FONTLIST); do echo '  '$LINE; done) \n\nProceed with installation?" \
+		32 96 16 \
 		--scrolltext) then
 		# Install loop
 		display_info 'Installing preferred fonts...'
@@ -22,8 +22,8 @@ function install_fonts {
 			if [ "" == "$PKGCHECK" ]; then
 				# Install package
 				display_info "'$PACKAGE' is not installed. Installing..."
-				display_warning 'Requires admin privileges'
-				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
+				# Admin privileges
+				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
 				# Done
 				display_success "'$PACKAGE' installation is complete."
 			else
@@ -33,7 +33,7 @@ function install_fonts {
 		done
 		# Finish
 		display_success "Installation complete."
-		whiptail --title "Finished" --msgbox "Installation complete." 8 78
+		whiptail --title "Finished" --msgbox "Installation complete." 8 64
 		fonts
 	else
 		fonts
@@ -51,16 +51,16 @@ function msttcorefonts {
 	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
 	if [ "" == "$PKGCHECK" ]; then
 		display_info $NAME 'is not installed. Installing...'
-		if (whiptail --title "Microsoft Core Fonts" --yesno "Install Microsoft Windows core fonts to extend font support?" 10 60) then
+		if (whiptail --title "Microsoft Core Fonts" --yesno "Install Microsoft Windows core fonts to extend font support?" 8 64) then
 			# Install
 			display_info 'Installing...'
-			display_warning 'Requires admin privileges'
-			$SUDOCMD apt install -y $PACKAGE
+			# Admin privileges
+			elevate_privilege "apt install -y $PACKAGE"
 			# Done
 			display_success 'Done.'
 			# Finished
 			display_success "'$NAME' is installation complete."
-			whiptail --title "Finished" --msgbox "Installation complete." 8 78
+			whiptail --title "Finished" --msgbox "Installation complete." 8 64
 			fonts
 		else
 			fonts
@@ -68,7 +68,7 @@ function msttcorefonts {
 	else
 		# Already installed
 		echo $NAME 'installed.'
-		whiptail --title "Finished" --msgbox "$NAME are installed." 8 78
+		whiptail --title "Finished" --msgbox "$NAME are installed." 8 64
 		fonts
 	fi
 }
@@ -76,19 +76,19 @@ function msttcorefonts {
 # Install Fonts
 function fonts {
 	display_title "Starting 'fonts' function..."
-	# Draw window
-	FONTS=$(eval `resize` && whiptail \
+	# check exit status
+	exitstatus=$?
+	if [ $exitstatus = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
 		--notags \
 		--title "Install Fonts" \
 		--menu "\nWhat would you like to do?" \
 		--cancel-button "Go Back" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		32 96 16 \
 		install_fonts	'Install favourite fonts' \
 		msttcorefonts	'Install Microsoft core fonts' \
 		3>&1 1>&2 2>&3)
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		$FONTS
 	else
 		main
 	fi
diff --git a/functions/gnome b/functions/gnome
--- a/functions/gnome
+++ b/functions/gnome
@@ -2,18 +2,21 @@
 
 # Add GNOME PPA
 function upgrade_gnome {
+	PPA=ppa:gnome3-team/gnome3
 	display_title "Starting 'upgrade_gnome' function..."
 	# Add repository
 	display_info 'Adding GNOME3 PPA to software sources...'
-	display_warning 'Requires admin privileges'
-	$SUDOCMD add-apt-repository -y ppa:gnome3-team/gnome3
+	# Admin privileges
+	elevate_privilege "add-apt-repository -y $PPA"
 	# Update repository information
 	display_info 'Updating repository information...'
-	$SUDOCMD apt update -y
+	# Admin privileges
+	elevate_privilege "apt update -y"
 	display_success 'Done.'
 	# Upgrade GNOME
 	display_info 'Upgrading GNOME software...'
-	$SUDOCMD apt dist-upgrade -y
+	# Admin privileges
+	elevate_privilege "apt dist-upgrade -y"
 	display_success "Upgrade complete."
 	gnome
 }
@@ -26,8 +29,8 @@ function install_gnome_desktop {
 	# Draw window
 	if (eval `resize` && whiptail \
 		--title "GNOME Desktop" \
-		--yesno "Packages to install for a basic GNOME desktop: \n\n$(cat $GNOMEDESKTOP) \n\nProceed with installation?" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		--yesno "Packages to install for a basic GNOME desktop: \n\n$(for LINE in $(cat $GNOMEDESKTOP); do echo '  '$LINE; done) \n\nProceed with installation?" \
+		32 96 16 \
 		--scrolltext) then
 		# Install loop
 		display_info 'Installing GNOME desktop...'
@@ -38,8 +41,8 @@ function install_gnome_desktop {
 			if [ "" == "$PKGCHECK" ]; then
 				# Install package
 				display_info "'$PACKAGE' is not installed. Installing..."
-				display_warning 'Requires admin privileges'
-				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
+				# Admin privileges
+				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
 				# Done
 				display_success "'$PACKAGE' installation is complete."
 			else
@@ -49,7 +52,7 @@ function install_gnome_desktop {
 		done
 		# Finish
 		display_success "Installation complete."
-		whiptail --title "Finished" --msgbox "Installation complete." 8 78
+		whiptail --title "Finished" --msgbox "Installation complete." 8 64
 		gnome
 	else
 		gnome
@@ -64,8 +67,8 @@ function install_gnome_apps {
 	# Draw window
 	if (eval `resize` && whiptail \
 		--title "GNOME Core Apps" \
-		--yesno "Current list of GNOME core apps: \n\n$(cat $GNOMEAPPS) \n\nWould you like to install these apps?" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		--yesno "Current list of GNOME core apps: \n\n$(for LINE in $(cat $GNOMEAPPS); do echo '  '$LINE; done) \n\nWould you like to install these apps?" \
+		32 96 16 \
 		--scrolltext ) then
 		# Install loop
 		display_info 'Installing GNOME core apps...'
@@ -76,8 +79,8 @@ function install_gnome_apps {
 			if [ "" == "$PKGCHECK" ]; then
 				# Install package
 				display_info "'$PACKAGE' is not installed. Installing..."
-				display_warning 'Requires admin privileges'
-				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
+				# Admin privileges
+				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
 				# Done
 				display_success "'$PACKAGE' installation is complete."
 			else
@@ -87,7 +90,7 @@ function install_gnome_apps {
 		done
 		# Finish
 		display_success "Installation complete."
-		whiptail --title "Finished" --msgbox "GNOME Apps are installed complete." 8 78
+		whiptail --title "Finished" --msgbox "GNOME Apps are installed complete." 8 64
 		gnome
 	else
 		gnome
@@ -97,21 +100,20 @@ function install_gnome_apps {
 # GNOME
 function gnome {
 	display_title "Starting 'gnome' function..."
-	# Draw window
-	GNOME=$(eval `resize` && whiptail \
+	# check exit status
+	exitstatus=$?
+	if [ $exitstatus = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
 		--notags \
 		--title "Install Latest GNOME" \
 		--menu "\nWhat would you like to do?" \
 		--cancel-button "Go Back" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		32 96 16 \
 		upgrade_gnome			'Update to latest GNOME' \
 		install_gnome_desktop	'Install basic GNOME desktop' \
 		install_gnome_apps		'Install GNOME core applications' \
 		3>&1 1>&2 2>&3)
-
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		$GNOME
 	else
 		main
 	fi
diff --git a/functions/thirdparty b/functions/thirdparty
--- a/functions/thirdparty
+++ b/functions/thirdparty
@@ -25,21 +25,24 @@ source $dir/functions/apps/synergy
 # Install Third-Party Applications
 function thirdparty {
 	display_title "Starting 'thirdparty' function..."
-	# Draw window
-	THIRDPARTY=$(eval `resize` && whiptail \
+	# check exit status
+	exitstatus=$?
+	if [ $exitstatus = 0 ]; then
+		# Draw window
+		$(eval `resize` && whiptail \
 		--notags \
 		--title "Third-Party Applications" \
-		--menu "\nWhat third-party apps would you like to install?" \
+		--menu "\nWhich third-party app would you like to install?" \
 		--ok-button "Install" \
 		--cancel-button "Go Back" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		32 96 16 \
 		'dropbox'		'Dropbox' \
 		'flatpak'		'Flatpak' \
 		'fontforge'		'FontForge' \
 		'google-chrome'	'Google Chrome' \
 		'inkscape'		'Inkscape' \
 		'minecraft'		'Minecraft' \
-		'oracle-java'	'Oracle Java' \
+		'oracle-java'	'Oracle Java 9' \
 		'peek'			'Peek' \
 		'plex'			'Plex Media Server' \
 		'riot'			'Riot Chat' \
@@ -50,10 +53,6 @@ function thirdparty {
 		'sublime-text'	'Sublime Text 3' \
 		'synergy'		'Synergy' \
 		3>&1 1>&2 2>&3)
-
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		$THIRDPARTY
 	else
 		main
 	fi
diff --git a/functions/utilities b/functions/utilities
--- a/functions/utilities
+++ b/functions/utilities
@@ -10,8 +10,8 @@ function install_utilities {
 	# Draw window
 	if (eval `resize` && whiptail --title \
 		"Preferred System Utilities"  --yesno \
-		"Current list of preferred system utilities: \n\n$(cat $UTILS) \n\nProceed with installation?" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		"Current list of preferred system utilities: \n\n$(for LINE in $(cat $UTILS); do echo '  '$LINE; done) \n\nProceed with installation?" \
+		32 96 16 \
 		--scrolltext ) then
 		# Install loop
 		display_info 'Installing preferred utilities...'
@@ -22,8 +22,8 @@ function install_utilities {
 			if [ "" == "$PKGCHECK" ]; then
 				# Install package
 				display_info "'$PACKAGE' is not installed. Installing..."
-				display_warning 'Requires admin privileges'
-				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
+				# Admin privileges
+				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
 				# Done
 				display_success "'$PACKAGE' installation is complete."
 			else
@@ -33,7 +33,7 @@ function install_utilities {
 		done
 		# Finish
 		display_success "Installation complete."
-		whiptail --title "Finished" --msgbox "Installation complete." 8 78
+		whiptail --title "Finished" --msgbox "Installation complete." 8 64
 		utilities
 	else
 		utilities
@@ -52,8 +52,8 @@ function node_packages {
 	# Draw window
 	if (eval `resize` && whiptail --title \
 		"Preferred System Utilities"  --yesno \
-		"Current list of preferred NodeJS-based tools: \n\n$(cat $NODE) \n\nProceed with installation?" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
+		"Current list of preferred NodeJS-based tools: \n\n$(for LINE in $(cat $NODE); do echo '  '$LINE; done) \n\nProceed with installation?" \
+		32 96 16 \
 		--scrolltext ) then
 		# Install loop
 		display_info 'Installing preferred NodeJS-based tools...'
@@ -64,8 +64,8 @@ function node_packages {
 			if [ "" == "$PKGCHECK" ]; then
 				# Install package
 				display_info "'$PACKAGE' is not installed. Installing..."
-				display_warning 'Requires admin privileges'
-				$SUDOCMD npm install -g $PACKAGE
+				# Admin privileges
+				elevate_privilege "npm install -g $PACKAGE"
 				# Done
 				display_success "'$PACKAGE' installation is complete."
 			else
@@ -75,7 +75,7 @@ function node_packages {
 		done
 		# Finish
 		display_success "Installation complete."
-		whiptail --title "Finished" --msgbox "Installation complete." 8 78
+		whiptail --title "Finished" --msgbox "Installation complete." 8 64
 		utilities
 	else
 		utilities
@@ -85,32 +85,29 @@ function node_packages {
 # Check for and install required packages for this script set.
 function node_check {
 	# Check list
-	NODEDEPS="nodejs nodejs-legacy"
+	NODEDEPS="npm"
 	for PACKAGE in $NODEDEPS; do
 		display_title "Checking if '$PACKAGE' is installed..."
 		PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
 		if [ "" == "$PKGCHECK" ]; then
 			display_warning "Dependency '$PACKAGE' is not present on your system and is required to continue."
-			display_question 'Would you like to install it now? (Y)es, (N)o :' && read REPLY
-			case $REPLY in
-			# Positive action
-			[Yy]* ) 
+			# Draw window
+			if (eval `resize` && whiptail \
+				--yesno \
+				--title "Dependency Check" \
+				--ok-button "Install" \
+				--cancel-button "Go Back" \
+				"In order to continue '$PACKAGE' needs to be installed. Continue?" 8 64 ) then
 				display_info "Intalling '$PACKAGE' installed. Proceeding."
-				display_warning 'Requires admin privileges'
-				$SUDOCMD apt -y install $PACKAGE
+				# Admin privileges
+				elevate_privilege "apt install -y $PACKAGE"
 				display_success "Package '$PACKAGE' installed. Proceeding."
-				;;
-			# Negative action
-			[Nn]* )
+			else
 				display_warning "Required dependencies are not present. :/"
-				echo "Exiting..."
-				exit 99
-				;;
-			# Error
-			* )
-				display_error '\aInvalid response, please try again.' && node_check
-				;;
-			esac
+				# Draw window
+				whiptail --msgbox "Required dependency '$PACKAGE' was not installed. Aborting. \nPlease try again." 8 64
+				utilities
+			fi
 		else
 			echo "Dependency '$PACKAGE' is installed."
 		fi
@@ -119,23 +116,22 @@ function node_check {
 	echo "Proceeding."
 }
 
-
 # Install utilities
 function utilities {
 	display_title "Starting 'utilities' function..."
-	# Draw window
-	CLEANUP=$(eval `resize`&& whiptail \
+	# check exit status
+	exitstatus=$?
+	if [ $exitstatus = 0 ]; then
+		# Draw window
+		$(eval `resize`&& whiptail \
 		--notags \
-		--title "System Cleanup" \
+		--title "Install Utilities" \
 		--menu "\nWhat would you like to do?" \
+		32 96 16 \
 		--cancel-button "Go Back" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
 		install_utilities	'Install preferred system utilities' \
 		node_packages		'Install NodeJS-based tools' \
 		3>&1 1>&2 2>&3)
-	exitstatus=$?
-	if [ $exitstatus = 0 ]; then
-		$CLEANUP
 	else
 		main
 	fi
